spring:
  springdoc:
    api-docs:
      version: 3.0.1
  datasource:
    url: jdbc:postgresql://${URL}
    #jdbc:postgresql://postgres:ladCwrOptmkkkIPbUumSDrckzdTjVIwl@caboose.proxy.rlwy.net:19109/railway
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.PostgreSQLDialect